#!/bin/bash

echo "=== Railway PostgreSQL Fix Script ==="
echo ""
echo "This script will help you fix the PostgreSQL authentication issue on Railway."
echo ""
echo "The problem is likely one of the following:"
echo "1. PostgreSQL service is not properly configured"
echo "2. Database user credentials are incorrect"
echo "3. Database permissions are not set correctly"
echo ""
echo "Please follow these steps:"
echo ""
echo "1. Go to your Railway dashboard"
echo "2. Find your PostgreSQL service"
echo "3. Go to the 'Data' tab"
echo "4. Click on 'Reset Database' to create a fresh database"
echo "5. Or go to 'Variables' tab and check if these variables exist:"
echo "   - PGHOST"
echo "   - PGPORT" 
echo "   - PGUSER"
echo "   - PGPASSWORD"
echo "   - PGDATABASE"
echo "   - DATABASE_URL"
echo ""
echo "6. If DATABASE_URL is missing, create it with this format:"
echo "   postgresql://username:password@host:port/database"
echo ""
echo "7. Make sure your backend service is connected to the PostgreSQL service:"
echo "   - Go to your backend service"
echo "   - Go to 'Settings' tab"
echo "   - Under 'Connected Services', make sure PostgreSQL is listed"
echo ""
echo "8. If the issue persists, try these commands in Railway's console:"
echo "   - Connect to your PostgreSQL service"
echo "   - Run: ALTER USER postgres PASSWORD 'your_new_password';"
echo "   - Run: GRANT ALL PRIVILEGES ON DATABASE your_database TO postgres;"
echo ""
echo "9. Alternative: Create a new user with proper permissions:"
echo "   CREATE USER your_app_user WITH PASSWORD 'your_password';"
echo "   GRANT ALL PRIVILEGES ON DATABASE your_database TO your_app_user;"
echo "   ALTER USER your_app_user CREATEDB;"
echo ""
echo "10. Update your DATABASE_URL to use the new user:"
echo "    postgresql://your_app_user:your_password@host:port/your_database"
echo ""
echo "After making these changes, redeploy your backend service."
echo ""
echo "If you need to test the connection locally, you can use:"
echo "psql 'your_database_url_here'"
echo ""
