const { PrismaClient } = require('@prisma/client');

// Ensure Prisma Client is properly initialized
let prisma;

try {
  prisma = new PrismaClient({
    datasources: {
      db: {
        url: process.env.DATABASE_URL
      }
    }
  });
} catch (error) {
  console.error('Failed to initialize Prisma Client:', error);
  console.error('Make sure Prisma Client is generated by running: npx prisma generate');
  throw error;
}

module.exports = prisma;
