const { PrismaClient } = require('@prisma/client');

// Ensure Prisma Client is properly initialized
let prisma;

try {
  // Log DATABASE_URL for debugging (without password)
  const dbUrl = process.env.DATABASE_URL;
  if (dbUrl) {
    const urlParts = new URL(dbUrl);
    console.log(`Connecting to database: ${urlParts.protocol}//${urlParts.hostname}:${urlParts.port}${urlParts.pathname}`);
  } else {
    console.warn('DATABASE_URL environment variable is not set');
  }

  prisma = new PrismaClient({
    datasources: {
      db: {
        url: dbUrl
      }
    },
    log: ['query', 'info', 'warn', 'error']
  });
} catch (error) {
  console.error('Failed to initialize Prisma Client:', error);
  console.error('Make sure Prisma Client is generated by running: npx prisma generate');
  throw error;
}

module.exports = prisma;
